package com.mb.info.req;

public enum WalletTransactionType {
    IN_CASHBACK, IN_EARNING, IN_DEFAULT_WALLET_AMOUNT_ON_CREATION, IN_REFERRAL_ON_SELF_REGISTRATION, IN_REFERRAL_ON_REFERRED_FIRST_ORDER, OUT_WITHDRAW, OUT_ORDER_PAYMENT, IN_ORDER_CANCELLED_REVERSAL;
}
