image: openjdk:8

pipelines:
  branches:
      master:
        - step:
            name: Prod build and deploy
            caches:
              - gradle
            script:
                - bash ./gradlew build
                - jarName=userapi-prod-`date '+%Y_%m_%d_%H_%M'`.jar
                - mv ./build/libs/userapi-0.0.1-SNAPSHOT.jar ./build/libs/$jarName 
                - scp -r ./build/libs/$jarName $USER@$HOST:$PROD_DIR
                - RUNNING_PID=$(ssh $USER@$HOST "lsof -t -i:$PROD_PORT -sTCP:LISTEN")
                - ssh $USER@$HOST "kill -9 $RUNNING_PID"
                - ssh $USER@$HOST "nohup java -jar $PROD_DIR/$jarName >> nohup.out 2>&1 &"